package etu.kefengroup.turistomer.utils;

import java.util.HashMap;
import java.util.Map;

public class EnglishToTurkishMappings {
    public static final Map<String, String> englishToTurkishCuisineMap = new HashMap<>();
    public static final Map<String, String> englishToTurkishAmenityMap = new HashMap<>();


    static {
        englishToTurkishCuisineMap.put("Medical Foods", "Tıbbi gıdalar");
        englishToTurkishCuisineMap.put("Mediterranean", "Akdeniz");
        englishToTurkishCuisineMap.put("Venezuela", "Venezuela");
        englishToTurkishCuisineMap.put("Native American", "Amerikan Yerli");
        englishToTurkishCuisineMap.put("Southern Italy", "Güney İtalya");
        englishToTurkishCuisineMap.put("Europe", "Avrupa");
        englishToTurkishCuisineMap.put("Nigeria", "Nijerya");
        englishToTurkishCuisineMap.put("Sri Lankan", "Sri Lankalı");
        englishToTurkishCuisineMap.put("Brazil", "Brezilya");
        englishToTurkishCuisineMap.put("Steakhouse", "Biftek Restoranı");
        englishToTurkishCuisineMap.put("German", "Alman");
        englishToTurkishCuisineMap.put("Japanese Fusion", "Japon Füzyonu");
        englishToTurkishCuisineMap.put("Mexico", "Meksika");
        englishToTurkishCuisineMap.put("Romania", "Romanya");
        englishToTurkishCuisineMap.put("Hawaii", "Hawai");
        englishToTurkishCuisineMap.put("Campania", "Campania");
        englishToTurkishCuisineMap.put("Spanish", "İspanyol");
        englishToTurkishCuisineMap.put("Italian", "İtalyan");
        englishToTurkishCuisineMap.put("Scottish", "İskoç");
        englishToTurkishCuisineMap.put("Fujian", "Fujian");
        englishToTurkishCuisineMap.put("Latin", "Latin");
        englishToTurkishCuisineMap.put("Pizza", "Pizza");
        englishToTurkishCuisineMap.put("Philippines", "Filipinler");
        englishToTurkishCuisineMap.put("Ecuador", "Ekvador");
        englishToTurkishCuisineMap.put("Costa Rica", "Kosta Rika");
        englishToTurkishCuisineMap.put("Colombia", "Kolombiya");
        englishToTurkishCuisineMap.put("Arab", "Arap");
        englishToTurkishCuisineMap.put("Assyrian", "Asur");
        englishToTurkishCuisineMap.put("Fusion", "Füzyon");
        englishToTurkishCuisineMap.put("Turkish", "Türk");
        englishToTurkishCuisineMap.put("Gastro Pubs", "Yemekli barlar");
        englishToTurkishCuisineMap.put("Armenian", "Ermeni");
        englishToTurkishCuisineMap.put("Jamaica", "Jamaika");
        englishToTurkishCuisineMap.put("Scandinavian", "İskandinav");
        englishToTurkishCuisineMap.put("Switzerland", "İsviçre");
        englishToTurkishCuisineMap.put("Northern Italy", "Kuzey İtalya");
        englishToTurkishCuisineMap.put("Middle East", "Ortadoğu");
        englishToTurkishCuisineMap.put("Japanese Sweet Shop", "Japon tatlı dükkânı");
        englishToTurkishCuisineMap.put("Lebanon", "Lübnan");
        englishToTurkishCuisineMap.put("Lombard", "Lombard");
        englishToTurkishCuisineMap.put("Southwest", "Güneybatı");
        englishToTurkishCuisineMap.put("Dutch", "Felemenk");
        englishToTurkishCuisineMap.put("Russian", "Rus");
        englishToTurkishCuisineMap.put("Barbecue", "Mangal");
        englishToTurkishCuisineMap.put("Cajun and Creole", "Cajun ve Creole");
        englishToTurkishCuisineMap.put("Greek", "Yunan");
        englishToTurkishCuisineMap.put("Beer Restaurants", "Bira restoranları");
        englishToTurkishCuisineMap.put("Croatian", "Hırvat");
        englishToTurkishCuisineMap.put("Poland", "Polonya");
        englishToTurkishCuisineMap.put("Ethiopia", "Etiyopya");
        englishToTurkishCuisineMap.put("Indonesia", "Endonezya");
        englishToTurkishCuisineMap.put("Street Food", "Sokak Yemekleri");
        englishToTurkishCuisineMap.put("Barbecue", "Barbekü");
        englishToTurkishCuisineMap.put("Catalan", "Katalan");
        englishToTurkishCuisineMap.put("Yunnan", "Yunnan");
        englishToTurkishCuisineMap.put("Morocco", "Fas");
        englishToTurkishCuisineMap.put("Taiwan", "Tayvan");
        englishToTurkishCuisineMap.put("Austria", "Avusturya");
        englishToTurkishCuisineMap.put("Iran", "İran");
        englishToTurkishCuisineMap.put("Asia", "Asya");
        englishToTurkishCuisineMap.put("Healthy", "Sağlıklı");
        englishToTurkishCuisineMap.put("China", "Çin");
        englishToTurkishCuisineMap.put("Fast Food", "Fast Food");
        englishToTurkishCuisineMap.put("Eastern Europe", "Doğu Avrupa");
        englishToTurkishCuisineMap.put("Seafood", "Deniz Mahsülleri");
        englishToTurkishCuisineMap.put("Georgian", "Gürcü");
        englishToTurkishCuisineMap.put("Brew Pub", "Brew Pub");
        englishToTurkishCuisineMap.put("Bar", "Bar");
        englishToTurkishCuisineMap.put("Azerbaijan", "Azerbaycan");
        englishToTurkishCuisineMap.put("Café", "Kafe");
        englishToTurkishCuisineMap.put("French", "Fransız");
        englishToTurkishCuisineMap.put("Emilia", "Emilia");
        englishToTurkishCuisineMap.put("Liguria", "Liguria");
        englishToTurkishCuisineMap.put("Deli", "Şarküteri");
        englishToTurkishCuisineMap.put("Xinjiang", "Xinjiang");
        englishToTurkishCuisineMap.put("Mongolian", "Moğol");
        englishToTurkishCuisineMap.put("Slovenian", "Sloven");
        englishToTurkishCuisineMap.put("Chile", "Şili");
        englishToTurkishCuisineMap.put("Africa", "Afrika");
        englishToTurkishCuisineMap.put("Denmark", "Danimarka");
        englishToTurkishCuisineMap.put("Vietnam", "Vietnam");
        englishToTurkishCuisineMap.put("Argentina", "Arjantin");
        englishToTurkishCuisineMap.put("Sushi", "Suşi");
        englishToTurkishCuisineMap.put("Peru", "Peru");
        englishToTurkishCuisineMap.put("Caribbean", "Karayipler");
        englishToTurkishCuisineMap.put("Portugal", "Portekiz");
        englishToTurkishCuisineMap.put("Balti", "Balti");
        englishToTurkishCuisineMap.put("Soups", "Çorbalar");
        englishToTurkishCuisineMap.put("Shojin", "Shojin");
        englishToTurkishCuisineMap.put("Ukraine", "Ukrayna");
        englishToTurkishCuisineMap.put("Sweden", "İsveç");
        englishToTurkishCuisineMap.put("Wine Bar", "Şarap Barı");
        englishToTurkishCuisineMap.put("Tunisia", "Tunus");
        englishToTurkishCuisineMap.put("South America", "Güney Amerika");
        englishToTurkishCuisineMap.put("Polynesia", "Polinezya");
        englishToTurkishCuisineMap.put("Hungarian", "Macar");
        englishToTurkishCuisineMap.put("Restaurant", "Lokanta");
        englishToTurkishCuisineMap.put("Malaysia", "Malezya");
        englishToTurkishCuisineMap.put("Naples", "Napoli");
        englishToTurkishCuisineMap.put("Albanian", "Arnavut");
        englishToTurkishCuisineMap.put("Beijing cuisine", "Pekin mutfağı");
        englishToTurkishCuisineMap.put("Belgium", "Belçika");
        englishToTurkishCuisineMap.put("Sicily", "Sicilya");
        englishToTurkishCuisineMap.put("Caucasian", "Kafkas");
        englishToTurkishCuisineMap.put("Ireland", "İrlanda");
        englishToTurkishCuisineMap.put("American", "Amerikan");
        englishToTurkishCuisineMap.put("Local", "Yöresel");
        englishToTurkishCuisineMap.put("Israel", "İsrail");
        englishToTurkishCuisineMap.put("Pakistan", "Pakistan");
        englishToTurkishCuisineMap.put("Australia", "Avustralya");
        englishToTurkishCuisineMap.put("Uzbek", "Özbek");
        englishToTurkishCuisineMap.put("Algeria", "Cezayir");
        englishToTurkishCuisineMap.put("Lazio", "Lazio");
        englishToTurkishCuisineMap.put("Latvia", "Letonya");
        englishToTurkishCuisineMap.put("Guatemala", "Guatemala");
        englishToTurkishCuisineMap.put("Central Asia", "Orta Asya");
        englishToTurkishCuisineMap.put("Norway", "Norveç");
        englishToTurkishCuisineMap.put("Cuba", "Küba");
        englishToTurkishCuisineMap.put("India", "Hint");
        englishToTurkishCuisineMap.put("Contemporary", "Çağdaş");
        englishToTurkishCuisineMap.put("Central Italy", "Orta İtalya");
        englishToTurkishCuisineMap.put("Korea", "Kore");
        englishToTurkishCuisineMap.put("Gastropub", "Gastropub");
        englishToTurkishCuisineMap.put("Japanese", "Japon");
        englishToTurkishCuisineMap.put("Central America", "Orta Amerika");
        englishToTurkishCuisineMap.put("Roman", "Romana");
        englishToTurkishCuisineMap.put("Afghan", "Afkan");
        englishToTurkishCuisineMap.put("Canada", "Kanada");
        englishToTurkishCuisineMap.put("Bahamas", "Bahama");
        englishToTurkishCuisineMap.put("English", "İngiliz");
        englishToTurkishCuisineMap.put("Central Europe", "Orta Avrupa");
        englishToTurkishCuisineMap.put("Tuscany", "Toskana");
        englishToTurkishCuisineMap.put("Tibet", "Tibet");
        englishToTurkishCuisineMap.put("Nepal", "Nepal");
        englishToTurkishCuisineMap.put("Sardinia", "Sardinya");
        englishToTurkishCuisineMap.put("Kyoto cuisine", "Kyoto mutfağı");
        englishToTurkishCuisineMap.put("Czech", "Çek");
        englishToTurkishCuisineMap.put("Fruit Shops", "Meyve dükkânları");
        englishToTurkishCuisineMap.put("Cambodia", "Kamboçya");
        englishToTurkishCuisineMap.put("Egypt", "Mısır");
        englishToTurkishCuisineMap.put("Thailand", "Tayland");
        englishToTurkishCuisineMap.put("Bangladesh", "Bangladeş");
        englishToTurkishCuisineMap.put("Galician", "Gal");
        englishToTurkishCuisineMap.put("International", "Uluslararası");

        englishToTurkishAmenityMap.put("Squash", "Squash");
        englishToTurkishAmenityMap.put("Pool/beach towels", "Havuz/plaj havluları");
        englishToTurkishAmenityMap.put("Yoga classes", "Yoga dersleri");
        englishToTurkishAmenityMap.put("Dishwasher", "Bulaşık makinesi");
        englishToTurkishAmenityMap.put("Free internet", "Ücretsiz internet");
        englishToTurkishAmenityMap.put("Separate living room", "Ayrı oturma odası");
        englishToTurkishAmenityMap.put("Books for children", "Çocuklar için kitaplar");
        englishToTurkishAmenityMap.put("Separate dining room", "Ayrı yemek salonu");
        englishToTurkishAmenityMap.put("BBQ areas", "Barbekü alanları");
        englishToTurkishAmenityMap.put("Bicycles available", "Bisiklet mevcut");
        englishToTurkishAmenityMap.put("Mosquito net", "Cibinlik");
        englishToTurkishAmenityMap.put("Concierge", "Concierge");
        englishToTurkishAmenityMap.put("Dry cleaning", "Kuru temizleme");
        englishToTurkishAmenityMap.put("Massage", "Masaj");
        englishToTurkishAmenityMap.put("Hand massage", "El masajı");
        englishToTurkishAmenityMap.put("Interconnecting rooms available", "Birbirine açılan odalar mevcut");
        englishToTurkishAmenityMap.put("Karaoke", "Karaoke");
        englishToTurkishAmenityMap.put("Buffet suitable for children", "Çocuklara uygun büfe");
        englishToTurkishAmenityMap.put("Children's play area", "Çocuklar için oyun alanı");
        englishToTurkishAmenityMap.put("Free High-Speed Internet (WiFi)", "Ücretsiz Yüksek Hızda İnternet (WiFi)");
        englishToTurkishAmenityMap.put("Sun terrace", "Güneşlenme alanı");
        englishToTurkishAmenityMap.put("Laundry service", "Çamaşır yıkama hizmeti");
        englishToTurkishAmenityMap.put("Nearby public free parking", "Yakınlarda halka açık ücretsiz otopark");
        englishToTurkishAmenityMap.put("Street parking", "Cadde üzerinde park");
        englishToTurkishAmenityMap.put("Cable/satellite TV", "Kablolu/uydu bağlantılı TV");
        englishToTurkishAmenityMap.put("Fishing", "Balık tutma");
        englishToTurkishAmenityMap.put("Pets allowed (Dogs/Pets Allowed)", "Evcil Hayvan Kabul Edilir (Köpeğe/Evcil Hayvanlara İzin Verilir)");
        englishToTurkishAmenityMap.put("Garden", "Bahçe");
        englishToTurkishAmenityMap.put("Yoga room", "Yoga odası");
        englishToTurkishAmenityMap.put("Shuttle bus service", "Servis otobüsü hizmeti");
        englishToTurkishAmenityMap.put("Video game console", "Video oyun konsolu");
        englishToTurkishAmenityMap.put("Luggage storage service", "Bagaj saklama hizmeti");
        englishToTurkishAmenityMap.put("Bathrobes", "Bornoz");
        englishToTurkishAmenityMap.put("Picnic area", "Piknik alanı");
        englishToTurkishAmenityMap.put("Jacuzzi bathtub", "Jakuzili küvet");
        englishToTurkishAmenityMap.put("Archery (off-site)", "Okçuluk (tesis dışında)");
        englishToTurkishAmenityMap.put("Water park", "Su parkı");
        englishToTurkishAmenityMap.put("Photocopy/fax services at the business center", "İş merkezinde fotokopi/faks");
        englishToTurkishAmenityMap.put("Shallow pool", "Derin ufak havuz");
        englishToTurkishAmenityMap.put("Water slide", "Su kaydırağı");
        englishToTurkishAmenityMap.put("Express check-in/check-out", "Hızlı giriş/çıkış");
        englishToTurkishAmenityMap.put("Stovetop", "Set Üstü Ocak");
        englishToTurkishAmenityMap.put("Boat tour", "Tekne turu");
        englishToTurkishAmenityMap.put("Infirmary", "Revir");
        englishToTurkishAmenityMap.put("Bathroom/shower", "Banyo/duş");
        englishToTurkishAmenityMap.put("Baby high chair available", "Bebek sandalyesi mevcut");
        englishToTurkishAmenityMap.put("Evening entertainment", "Gece eğlencesi");
        englishToTurkishAmenityMap.put("Stroller", "Puset");
        englishToTurkishAmenityMap.put("On-site ATM", "Tesis içi ATM");
        englishToTurkishAmenityMap.put("Air conditioning", "Klima");
        englishToTurkishAmenityMap.put("Small kitchen", "Küçük mutfak");
        englishToTurkishAmenityMap.put("Massage chair", "Masaj koltuğu");
        englishToTurkishAmenityMap.put("Honeymoon suite", "Balayı süiti");
        englishToTurkishAmenityMap.put("Waxing services", "Ağda hizmetleri");
        englishToTurkishAmenityMap.put("Walk-in shower", "Yerle aynı hizada duş");
        englishToTurkishAmenityMap.put("Solarium", "Solaryum");
        englishToTurkishAmenityMap.put("Archery", "Okçuluk");
        englishToTurkishAmenityMap.put("Dining room", "Yemek salonu");
        englishToTurkishAmenityMap.put("Work desk", "Çalışma masası");
        englishToTurkishAmenityMap.put("Pool with shallow end", "Sığ kısmı bulunan havuz");
        englishToTurkishAmenityMap.put("Saltwater pool", "Tuzlu su havuzu");
        englishToTurkishAmenityMap.put("Car rental", "Araba kiralama");
        englishToTurkishAmenityMap.put("Newspaper", "Gazete");
        englishToTurkishAmenityMap.put("Turkish bath", "Hamam");
        englishToTurkishAmenityMap.put("Tennis court", "Tenis kortu");
        englishToTurkishAmenityMap.put("Washing machine", "Çamaşır makinesi");
        englishToTurkishAmenityMap.put("Bicycle tours", "Bisiklet turları");
        englishToTurkishAmenityMap.put("Golf course", "Golf sahası");
        englishToTurkishAmenityMap.put("Wardrobe/closet", "Gardırop/elbise dolabı");
        englishToTurkishAmenityMap.put("Clothes rack", "Elbise askısı");
        englishToTurkishAmenityMap.put("On-site paid public parking", "Tesis içi halka açık ücretli otopark");
        englishToTurkishAmenityMap.put("Additional bathroom", "Ek banyo");
        englishToTurkishAmenityMap.put("Happy hour", "İndirimli içki saati");
        englishToTurkishAmenityMap.put("Iconic point view", "Simgesel nokta manzarası");
        englishToTurkishAmenityMap.put("Market", "Market");
        englishToTurkishAmenityMap.put("Gift shop", "Hediyelik eşya dükkanı");
        englishToTurkishAmenityMap.put("Family rooms", "Aile odaları");
        englishToTurkishAmenityMap.put("Hypoallergenic room", "Alerjensiz oda");
        englishToTurkishAmenityMap.put("Telephone", "Telefon");
        englishToTurkishAmenityMap.put("Bottled water", "Şişe suyu");
        englishToTurkishAmenityMap.put("Safe", "Kasa");
        englishToTurkishAmenityMap.put("Nature walk", "Doğa yürüyüşü");
        englishToTurkishAmenityMap.put("Darts", "Dart");
        englishToTurkishAmenityMap.put("Ski school", "Kayak okulu");
        englishToTurkishAmenityMap.put("Game room", "Oyun salonu");
        englishToTurkishAmenityMap.put("Coffee shop", "Kahve dükkanı");
        englishToTurkishAmenityMap.put("First aid kit", "İlk yardım çantası");
        englishToTurkishAmenityMap.put("Free shuttle or taxi services", "Ücretsiz servis veya taksi hizmetleri");
        englishToTurkishAmenityMap.put("Water sports equipment rental", "Su sporları ekipmanı kiralama");
        englishToTurkishAmenityMap.put("Mini golf", "Mini golf");
        englishToTurkishAmenityMap.put("Shops", "Dükkanlar");
        englishToTurkishAmenityMap.put("Secure parking", "Güvenli otopark");
        englishToTurkishAmenityMap.put("Fireplace", "Şömine");
        englishToTurkishAmenityMap.put("Outdoor fireplace", "Açık hava şöminesi");
        englishToTurkishAmenityMap.put("Canoeing", "Kano");
        englishToTurkishAmenityMap.put("Buffet breakfast", "Açık büfe kahvaltı");
        englishToTurkishAmenityMap.put("Electric kettle", "Elektrikli su ısıtıcısı");
        englishToTurkishAmenityMap.put("Bar/lounge", "Bar/oturma salonu");
        englishToTurkishAmenityMap.put("Steam room", "Buhar odası");
        englishToTurkishAmenityMap.put("Swimming pool toys", "Yüzme havuzu oyuncakları");
        englishToTurkishAmenityMap.put("Squash (off-site)", "Squash (tesis dışında)");
        englishToTurkishAmenityMap.put("Jacuzzi", "Jakuzi");
        englishToTurkishAmenityMap.put("Swim-up bar", "Yüzen bar");
        englishToTurkishAmenityMap.put("Private pool", "Özel havuz");
        englishToTurkishAmenityMap.put("Breakfast in room", "Odaya kahvaltı");
        englishToTurkishAmenityMap.put("Rooftop pool", "Çatı havuzu");
        englishToTurkishAmenityMap.put("Pedicure", "Pedikür");
        englishToTurkishAmenityMap.put("Umbrella", "Şemsiye");
        englishToTurkishAmenityMap.put("Public Wi-Fi", "Halka açık Wi-Fi");
        englishToTurkishAmenityMap.put("Vending machine", "Otomat");
        englishToTurkishAmenityMap.put("Lounge", "Salon");
        englishToTurkishAmenityMap.put("On-site private parking (surcharge)", "Tesis içinde ücretli özel otopark");
        englishToTurkishAmenityMap.put("Paid internet", "Ücretli internet");
        englishToTurkishAmenityMap.put("Suites", "Süitler");
        englishToTurkishAmenityMap.put("Aerobics (off-site)", "Aerobik (tesis dışında)");
        englishToTurkishAmenityMap.put("Free breakfast", "Ücretsiz kahvaltı");
        englishToTurkishAmenityMap.put("Sofa", "Kanepe");
        englishToTurkishAmenityMap.put("Wi-Fi", "Wi-Fi");
        englishToTurkishAmenityMap.put("Ski-in/ski-out", "Kayak Oteli");
        englishToTurkishAmenityMap.put("Taxi service", "Taksi servisi");
        englishToTurkishAmenityMap.put("Pool view", "Havuz manzaralı");
        englishToTurkishAmenityMap.put("Restaurant", "Restoran");
        englishToTurkishAmenityMap.put("Free nearby private parking", "Yakınlarda ücretsiz özel otopark");
        englishToTurkishAmenityMap.put("Outdoor bath", "Açık hava banyosu");
        englishToTurkishAmenityMap.put("Non-smoking hotel", "Sigara içilmeyen otel");
        englishToTurkishAmenityMap.put("Snack bar", "Atıştırmalık büfesi");
        englishToTurkishAmenityMap.put("Billiards", "Bilardo");
        englishToTurkishAmenityMap.put("24-hour security", "24 saat güvenlik");
        englishToTurkishAmenityMap.put("Skiing", "Kayak");
        englishToTurkishAmenityMap.put("Parking", "Otopark");
        englishToTurkishAmenityMap.put("Outdoor furniture", "Açık hava mobilyaları");
        englishToTurkishAmenityMap.put("Aerobics", "Aerobik");
        englishToTurkishAmenityMap.put("Hot spring bath", "Kaplıca havuzu");
        englishToTurkishAmenityMap.put("Indoor play area for children", "Çocuklar için kapalı oyun alanı");
        englishToTurkishAmenityMap.put("Free airport transportation", "Ücretsiz havaalanı ulaşım hizmeti");
        englishToTurkishAmenityMap.put("Free parking", "Ücretsiz otopark");
        englishToTurkishAmenityMap.put("Wine/champagne", "Şarap/şampanya");
        englishToTurkishAmenityMap.put("Private beach", "Özel plaj");
        englishToTurkishAmenityMap.put("Room service", "Oda servisi");
        englishToTurkishAmenityMap.put("Pool", "Havuz");
        englishToTurkishAmenityMap.put("Children's pool", "Çocuk havuzu");
        englishToTurkishAmenityMap.put("Complimentary welcome drink", "Ücretsiz karşılama içeceği");
        englishToTurkishAmenityMap.put("Children's Activities (Kid-friendly/Family-friendly)", "Çocuk Aktiviteleri (Çocuğa/Aileye Uygun)");
        englishToTurkishAmenityMap.put("Pay-per-view movies", "Ismarlanabilen filmler");
        englishToTurkishAmenityMap.put("Bicycle rental", "Bisiklet kiralama");
        englishToTurkishAmenityMap.put("Mountain view", "Dağ manzaralı");
        englishToTurkishAmenityMap.put("Room service", "Oda hizmeti");
        englishToTurkishAmenityMap.put("Safe", "Lostra");
        englishToTurkishAmenityMap.put("City view", "Şehir manzaralı");
        englishToTurkishAmenityMap.put("Facials", "Yüz bakımları");
        englishToTurkishAmenityMap.put("Indoor pool", "Kapalı havuz");
        englishToTurkishAmenityMap.put("Personal trainer available", "Size özel antrenör");
        englishToTurkishAmenityMap.put("Diving", "Dalış");
        englishToTurkishAmenityMap.put("Ocean view", "Okyanus manzarası");
        englishToTurkishAmenityMap.put("Children's meals", "Çocuk yemekleri");
        englishToTurkishAmenityMap.put("Clothes dryer", "Çamaşır kurutma makinesi");
        englishToTurkishAmenityMap.put("Private balcony", "Özel balkon");
        englishToTurkishAmenityMap.put("Shared kitchen", "Ortak mutfak");
        englishToTurkishAmenityMap.put("Electric vehicle charging station", "Elektrikli araç şarj istasyonu");
        englishToTurkishAmenityMap.put("Free Wi-Fi at the business center", "İş merkezinde ücretsiz kablosuz ağ");
        englishToTurkishAmenityMap.put("DVDs", "DVD’ler");
        englishToTurkishAmenityMap.put("Soundproof rooms", "Ses geçirmez odalar");
        englishToTurkishAmenityMap.put("Business section with internet access", "İnternet Bağlantılı İş Amaçlı Bölüm");
        englishToTurkishAmenityMap.put("Refrigerator", "Buzdolabı");
        englishToTurkishAmenityMap.put("Makeup services", "Makyaj hizmetleri");
        englishToTurkishAmenityMap.put("Ski rental", "Kayak kiralama");
        englishToTurkishAmenityMap.put("Wake-up service/alarm clock", "Uyandırma servisi/çalar saat");
        englishToTurkishAmenityMap.put("Sauna", "Sauna");
        englishToTurkishAmenityMap.put("Fitness center with gym/workout room", "Spor Salonlu/Spor Odalı Fitness Merkezi");
        englishToTurkishAmenityMap.put("Extra long beds", "Ekstra uzun yataklar");
        englishToTurkishAmenityMap.put("Pool with railing", "Parmaklıkla çevrili havuz");
        englishToTurkishAmenityMap.put("Foot bath", "Ayak banyosu");
        englishToTurkishAmenityMap.put("Hairdryer", "Saç kurutma makinesi");
        englishToTurkishAmenityMap.put("Full body massage", "Tam vücut masajı");
        englishToTurkishAmenityMap.put("Table tennis", "Masa tenisi");
        englishToTurkishAmenityMap.put("Adult pool", "Yetişkin havuzu");
        englishToTurkishAmenityMap.put("Board games/puzzles", "Masa oyunları/yapbozlar");
        englishToTurkishAmenityMap.put("Air purifier", "Hava temizleme cihazı");
        englishToTurkishAmenityMap.put("Bowling (off-site)", "Bovling (tesis dışında)");
        englishToTurkishAmenityMap.put("Outdoor play equipment for children", "Çocuklar için açık hava oyun ekipmanı");
        englishToTurkishAmenityMap.put("Infinity pool", "Sınırsız havuz");
        englishToTurkishAmenityMap.put("Tennis court (off-site)", "Tenis kortu (tesis dışında)");
        englishToTurkishAmenityMap.put("Nightclub/DJ", "Gece Kulübü/DJ");
        englishToTurkishAmenityMap.put("Head massage", "Baş masajı");
        englishToTurkishAmenityMap.put("Walking tours", "Yürüyüş turları");
        englishToTurkishAmenityMap.put("Breakfast available", "Kahvaltı mevcut");
        englishToTurkishAmenityMap.put("Badminton", "Badminton");
        englishToTurkishAmenityMap.put("Laptop safe", "Dizüstü bilgisayar kasası");
        englishToTurkishAmenityMap.put("Sun loungers/beach chairs", "Şezlonglar/plaj sandalyeleri");
        englishToTurkishAmenityMap.put("Shared lounge/TV area", "Ortak oturma/televizyon izleme alanı");
        englishToTurkishAmenityMap.put("Free Instant Coffee", "Ücretsiz Hazır Kahve");
        englishToTurkishAmenityMap.put("Spa", "Spa");
        englishToTurkishAmenityMap.put("Oven", "Fırın");
        englishToTurkishAmenityMap.put("Table tennis (off-site)", "Duvar tenisi (tesis dışında)");
        englishToTurkishAmenityMap.put("Windsurfing", "Rüzgar sörfü");
        englishToTurkishAmenityMap.put("Casino and Gambling", "Casino ve Talih Oyunları");
        englishToTurkishAmenityMap.put("Butler service", "Uşak hizmeti");
        englishToTurkishAmenityMap.put("Babysitting", "Bebek bakımı");
        englishToTurkishAmenityMap.put("Airport transportation service", "Havaalanı ulaşım hizmeti");
        englishToTurkishAmenityMap.put("Heated pool", "Isıtmalı havuz");
        englishToTurkishAmenityMap.put("Duty room", "Görevli odası");
        englishToTurkishAmenityMap.put("Kid-friendly TV channels", "Çocuklara uygun televizyon kanalları");
        englishToTurkishAmenityMap.put("Conference room", "Konferans salonu");
        englishToTurkishAmenityMap.put("Rooftop bar", "Çatı barı");
        englishToTurkishAmenityMap.put("Tile/marble floor", "Karo/mermer zemin");
        englishToTurkishAmenityMap.put("Foot massage", "Ayak masajı");
        englishToTurkishAmenityMap.put("Rooftop terrace", "Çatı katı terası");
        englishToTurkishAmenityMap.put("Free wired internet in the business center", "İş merkezinde ücretsiz kablolu internet");
        englishToTurkishAmenityMap.put("Music", "müzikler");
        englishToTurkishAmenityMap.put("Fitness/spa changing rooms", "Fitness/spa soyunma odaları");
        englishToTurkishAmenityMap.put("Bowling", "Bovling");
        englishToTurkishAmenityMap.put("Sun umbrellas", "Güneş şemsiyeleri");
        englishToTurkishAmenityMap.put("Private lounge facility", "Özel bekleme salonu olanağı");
        englishToTurkishAmenityMap.put("Electric blanket", "Elektrikli battaniye");
        englishToTurkishAmenityMap.put("Poolside bar", "Havuz kenarı barı");
        englishToTurkishAmenityMap.put("Outdoor pool", "Açık havuz");
        englishToTurkishAmenityMap.put("Animation team", "Animasyon ekibi");
        englishToTurkishAmenityMap.put("Currency exchange", "Döviz bozdurma");
        englishToTurkishAmenityMap.put("iPod dock", "iPod yuvası");
        englishToTurkishAmenityMap.put("VIP room amenities", "VIP oda olanakları");
        englishToTurkishAmenityMap.put("Seating area", "Oturma alanı");
        englishToTurkishAmenityMap.put("Flat-screen TV", "Düz Ekran Televizyon");
        englishToTurkishAmenityMap.put("Table tennis", "Duvar tenisi");
        englishToTurkishAmenityMap.put("Neck massage", "Boyun masajı");
        englishToTurkishAmenityMap.put("Slow-flowing river in the water park", "Su parkında yavaş akan nehir");
        englishToTurkishAmenityMap.put("Ironing service", "Ütü hizmeti");
        englishToTurkishAmenityMap.put("Horse riding", "Ata binme");
        englishToTurkishAmenityMap.put("Free tea", "Ücretsiz çay");
        englishToTurkishAmenityMap.put("Multi-storey parking", "Katlı otopark");
        englishToTurkishAmenityMap.put("Special diet menus", "Özel diyet menüleri");
        englishToTurkishAmenityMap.put("Pool with a view", "Manzaralı havuz");
        englishToTurkishAmenityMap.put("Manicure", "Manikür");
        englishToTurkishAmenityMap.put("Microwave oven", "Mikrodalga fırın");
        englishToTurkishAmenityMap.put("Free toiletries and personal care products", "Ücretsiz banyo ve kişisel bakım malzemeleri");
        englishToTurkishAmenityMap.put("Canoeing trip (off-site)", "Kano gezintisi (tesis dışında)");
        englishToTurkishAmenityMap.put("Valet parking service", "Vale park hizmeti");
        englishToTurkishAmenityMap.put("Mini bar", "Mini bar");
        englishToTurkishAmenityMap.put("Smoking rooms available", "Sigara içilebilen odalar mevcut");
        englishToTurkishAmenityMap.put("Snorkeling", "Şnorkelli dalış");
        englishToTurkishAmenityMap.put("Nearby paid public parking", "Yakınlarda ücretli halka açık otopark");
        englishToTurkishAmenityMap.put("Paid Wi-Fi", "Ücretli Wi-Fi");
        englishToTurkishAmenityMap.put("Sunbathing terrace", "Güneşlenme terası");
        englishToTurkishAmenityMap.put("24-hour check-in option", "24 saat giriş olanağı");
        englishToTurkishAmenityMap.put("Private bathrooms", "Özel banyolar");
        englishToTurkishAmenityMap.put("24-hour front desk", "24 saat açık resepsiyon");
        englishToTurkishAmenityMap.put("Phototherapy", "Fototerapi");
        englishToTurkishAmenityMap.put("Coffee/tea maker", "Kahve/çay makinesi");
        englishToTurkishAmenityMap.put("Outdoor dining area", "Açık hava yemek salonu");
        englishToTurkishAmenityMap.put("Private entrance/exit", "Özel giriş/çıkış");
        englishToTurkishAmenityMap.put("Nearby paid private parking", "Yakınlarda ücretli özel otopark");
        englishToTurkishAmenityMap.put("Water park (off-site)", "Su parkı (tesis dışında)");
        englishToTurkishAmenityMap.put("Kids' club", "Çocuk kulübü");
        englishToTurkishAmenityMap.put("Shared bathroom", "Ortak banyo");
        englishToTurkishAmenityMap.put("Fitness classes", "Fitness kursları");
        englishToTurkishAmenityMap.put("Blackout curtains", "Karartma perdeleri");
        englishToTurkishAmenityMap.put("Self-service laundry", "Self servis çamaşırhane");
        englishToTurkishAmenityMap.put("Adults only", "Yalnızca yetişkinler için");
        englishToTurkishAmenityMap.put("Bidet", "Bide");
        englishToTurkishAmenityMap.put("Couples massage", "Çiftler için masaj");
        englishToTurkishAmenityMap.put("Place of worship", "İbadet yeri");
        englishToTurkishAmenityMap.put("Non-smoking rooms", "Sigara içilmeyen odalar");
        englishToTurkishAmenityMap.put("Kitchenware", "Mutfak eşyaları");
        englishToTurkishAmenityMap.put("Door attendant", "Kapı görevlisi");
        englishToTurkishAmenityMap.put("Meeting rooms", "Toplantı odaları");
        englishToTurkishAmenityMap.put("Beach", "Plaj");
        englishToTurkishAmenityMap.put("Iron", "Ütü");
        englishToTurkishAmenityMap.put("Internet", "İnternet");
        englishToTurkishAmenityMap.put("Radio", "Radyo");
        englishToTurkishAmenityMap.put("Free stay for children", "Çocuklara ücretsiz konaklama");
        englishToTurkishAmenityMap.put("Body mask", "Vücut maskesi");
    }
}
