package etu.kefengroup.turistomer.utils;

import java.util.HashMap;
import java.util.Map;

public class EnglishToTurkishMappings {
    public static final Map<String, String> englishToTurkishMap = new HashMap<>();

    static {
        englishToTurkishMap.put("Medical Foods", "Tıbbi gıdalar");
        englishToTurkishMap.put("Mediterranean", "Akdeniz");
        englishToTurkishMap.put("Venezuela", "Venezuela");
        englishToTurkishMap.put("Native American", "Amerikan Yerli");
        englishToTurkishMap.put("Southern Italy", "Güney İtalya");
        englishToTurkishMap.put("Europe", "Avrupa");
        englishToTurkishMap.put("Nigeria", "Nijerya");
        englishToTurkishMap.put("Sri Lankan", "Sri Lankalı");
        englishToTurkishMap.put("Brazil", "Brezilya");
        englishToTurkishMap.put("Steakhouse", "Biftek Restoranı");
        englishToTurkishMap.put("German", "Alman");
        englishToTurkishMap.put("Japanese Fusion", "Japon Füzyonu");
        englishToTurkishMap.put("Mexico", "Meksika");
        englishToTurkishMap.put("Romania", "Romanya");
        englishToTurkishMap.put("Hawaii", "Hawai");
        englishToTurkishMap.put("Campania", "Campania");
        englishToTurkishMap.put("Spanish", "İspanyol");
        englishToTurkishMap.put("Italian", "İtalyan");
        englishToTurkishMap.put("Scottish", "İskoç");
        englishToTurkishMap.put("Fujian", "Fujian");
        englishToTurkishMap.put("Latin", "Latin");
        englishToTurkishMap.put("Pizza", "Pizza");
        englishToTurkishMap.put("Philippines", "Filipinler");
        englishToTurkishMap.put("Ecuador", "Ekvador");
        englishToTurkishMap.put("Costa Rica", "Kosta Rika");
        englishToTurkishMap.put("Colombia", "Kolombiya");
        englishToTurkishMap.put("Arab", "Arap");
        englishToTurkishMap.put("Assyrian", "Asur");
        englishToTurkishMap.put("Fusion", "Füzyon");
        englishToTurkishMap.put("Turkish", "Türk");
        englishToTurkishMap.put("Gastro Pubs", "Yemekli barlar");
        englishToTurkishMap.put("Armenian", "Ermeni");
        englishToTurkishMap.put("Jamaica", "Jamaika");
        englishToTurkishMap.put("Scandinavian", "İskandinav");
        englishToTurkishMap.put("Switzerland", "İsviçre");
        englishToTurkishMap.put("Northern Italy", "Kuzey İtalya");
        englishToTurkishMap.put("Middle East", "Ortadoğu");
        englishToTurkishMap.put("Japanese Sweet Shop", "Japon tatlı dükkânı");
        englishToTurkishMap.put("Lebanon", "Lübnan");
        englishToTurkishMap.put("Lombard", "Lombard");
        englishToTurkishMap.put("Southwest", "Güneybatı");
        englishToTurkishMap.put("Dutch", "Felemenk");
        englishToTurkishMap.put("Russian", "Rus");
        englishToTurkishMap.put("Barbecue", "Mangal");
        englishToTurkishMap.put("Cajun and Creole", "Cajun ve Creole");
        englishToTurkishMap.put("Greek", "Yunan");
        englishToTurkishMap.put("Beer Restaurants", "Bira restoranları");
        englishToTurkishMap.put("Croatian", "Hırvat");
        englishToTurkishMap.put("Poland", "Polonya");
        englishToTurkishMap.put("Ethiopia", "Etiyopya");
        englishToTurkishMap.put("Indonesia", "Endonezya");
        englishToTurkishMap.put("Street Food", "Sokak Yemekleri");
        englishToTurkishMap.put("Barbecue", "Barbekü");
        englishToTurkishMap.put("Catalan", "Katalan");
        englishToTurkishMap.put("Yunnan", "Yunnan");
        englishToTurkishMap.put("Morocco", "Fas");
        englishToTurkishMap.put("Taiwan", "Tayvan");
        englishToTurkishMap.put("Austria", "Avusturya");
        englishToTurkishMap.put("Iran", "İran");
        englishToTurkishMap.put("Asia", "Asya");
        englishToTurkishMap.put("Healthy", "Sağlıklı");
        englishToTurkishMap.put("China", "Çin");
        englishToTurkishMap.put("Fast Food", "Fast Food");
        englishToTurkishMap.put("Eastern Europe", "Doğu Avrupa");
        englishToTurkishMap.put("Seafood", "Deniz Mahsülleri");
        englishToTurkishMap.put("Georgian", "Gürcü");
        englishToTurkishMap.put("Brew Pub", "Brew Pub");
        englishToTurkishMap.put("Bar", "Bar");
        englishToTurkishMap.put("Azerbaijan", "Azerbaycan");
        englishToTurkishMap.put("Café", "Kafe");
        englishToTurkishMap.put("French", "Fransız");
        englishToTurkishMap.put("Emilia", "Emilia");
        englishToTurkishMap.put("Liguria", "Liguria");
        englishToTurkishMap.put("Deli", "Şarküteri");
        englishToTurkishMap.put("Xinjiang", "Xinjiang");
        englishToTurkishMap.put("Mongolian", "Moğol");
        englishToTurkishMap.put("Slovenian", "Sloven");
        englishToTurkishMap.put("Chile", "Şili");
        englishToTurkishMap.put("Africa", "Afrika");
        englishToTurkishMap.put("Denmark", "Danimarka");
        englishToTurkishMap.put("Vietnam", "Vietnam");
        englishToTurkishMap.put("Argentina", "Arjantin");
        englishToTurkishMap.put("Sushi", "Suşi");
        englishToTurkishMap.put("Peru", "Peru");
        englishToTurkishMap.put("Caribbean", "Karayipler");
        englishToTurkishMap.put("Portugal", "Portekiz");
        englishToTurkishMap.put("Balti", "Balti");
        englishToTurkishMap.put("Soups", "Çorbalar");
        englishToTurkishMap.put("Shojin", "Shojin");
        englishToTurkishMap.put("Ukraine", "Ukrayna");
        englishToTurkishMap.put("Sweden", "İsveç");
        englishToTurkishMap.put("Wine Bar", "Şarap Barı");
        englishToTurkishMap.put("Tunisia", "Tunus");
        englishToTurkishMap.put("South America", "Güney Amerika");
        englishToTurkishMap.put("Polynesia", "Polinezya");
        englishToTurkishMap.put("Hungarian", "Macar");
        englishToTurkishMap.put("Restaurant", "Lokanta");
        englishToTurkishMap.put("Malaysia", "Malezya");
        englishToTurkishMap.put("Naples", "Napoli");
        englishToTurkishMap.put("Albanian", "Arnavut");
        englishToTurkishMap.put("Beijing cuisine", "Pekin mutfağı");
        englishToTurkishMap.put("Belgium", "Belçika");
        englishToTurkishMap.put("Sicily", "Sicilya");
        englishToTurkishMap.put("Caucasian", "Kafkas");
        englishToTurkishMap.put("Ireland", "İrlanda");
        englishToTurkishMap.put("American", "Amerikan");
        englishToTurkishMap.put("Local", "Yöresel");
        englishToTurkishMap.put("Israel", "İsrail");
        englishToTurkishMap.put("Pakistan", "Pakistan");
        englishToTurkishMap.put("Australia", "Avustralya");
        englishToTurkishMap.put("Uzbek", "Özbek");
        englishToTurkishMap.put("Algeria", "Cezayir");
        englishToTurkishMap.put("Lazio", "Lazio");
        englishToTurkishMap.put("Latvia", "Letonya");
        englishToTurkishMap.put("Guatemala", "Guatemala");
        englishToTurkishMap.put("Central Asia", "Orta Asya");
        englishToTurkishMap.put("Norway", "Norveç");
        englishToTurkishMap.put("Cuba", "Küba");
        englishToTurkishMap.put("India", "Hint");
        englishToTurkishMap.put("Contemporary", "Çağdaş");
        englishToTurkishMap.put("Central Italy", "Orta İtalya");
        englishToTurkishMap.put("Korea", "Kore");
        englishToTurkishMap.put("Gastropub", "Gastropub");
        englishToTurkishMap.put("Japanese", "Japon");
        englishToTurkishMap.put("Central America", "Orta Amerika");
        englishToTurkishMap.put("Roman", "Romana");
        englishToTurkishMap.put("Afghan", "Afkan");
        englishToTurkishMap.put("Canada", "Kanada");
        englishToTurkishMap.put("Bahamas", "Bahama");
        englishToTurkishMap.put("English", "İngiliz");
        englishToTurkishMap.put("Central Europe", "Orta Avrupa");
        englishToTurkishMap.put("Tuscany", "Toskana");
        englishToTurkishMap.put("Tibet", "Tibet");
        englishToTurkishMap.put("Nepal", "Nepal");
        englishToTurkishMap.put("Sardinia", "Sardinya");
        englishToTurkishMap.put("Kyoto cuisine", "Kyoto mutfağı");
        englishToTurkishMap.put("Czech", "Çek");
        englishToTurkishMap.put("Fruit Shops", "Meyve dükkânları");
        englishToTurkishMap.put("Cambodia", "Kamboçya");
        englishToTurkishMap.put("Egypt", "Mısır");
        englishToTurkishMap.put("Thailand", "Tayland");
        englishToTurkishMap.put("Bangladesh", "Bangladeş");
        englishToTurkishMap.put("Galician", "Gal");
        englishToTurkishMap.put("International", "Uluslararası");
    }
}
